# SPDX-License-Identifier: ice License 1.0

development: true
logger:
  encoder: console
  level: debug
tokenomics:
  miningSessionDuration:
    max: 24h
  extraBonuses:
    duration: 24h
miner:
  ethereumDistributionFrequency:
    min: 24h
    max: 672h